bun + sveltekit = <3
replit/nixmodules pull request #105
Opened 2023-09-15 20:58 UTC by cdmistman

Why
===

i like bun

i like sveltekit

i like bun and sveltekit

they're better together <3

What changed
============

added new `bun-sveltekit` module

Test plan
=========

- install in sveltekit template
- things still work

Rollout
=======

_Describe any procedures or requirements needed to roll this out safely (or check the box below)_

- [ ] This is fully backward and forward compatible

2023-09-15 21:04 UTC, ryantm approved these changes

2023-09-16 02:15 UTC, masad-frost requested changes

2023-09-16 02:15 UTC, masad-frost commented on pkgs/modules/svelte-kit/bun.nix
> +      start = "${pkgs-unstable.nodePackages.svelte-language-server}/bin/svelteserver --stdio";
We shouldn't have this as a module, sveltekit should be installed in user's directory, not pulled from nix. I think more often than not, frameworks don't belong to this repo.

2023-09-16 02:26 UTC, masad-frost commented
we should lean on `bun create` in this case and templates

2023-09-16 03:33 UTC, masad-frost approved these changes
I misread what this is doing. :shipit:

2024-12-19 23:19 UTC, closed without merging