all the package managers
replit/nixmodules pull request #144
Opened 2023-10-20 21:51 UTC by cdmistman

Why
===

it doesn't make sense for only `npm` to be available in nodejs repls. users should have choice!

https://linear.app/replit/issue/DX-240/add-all-package-managers-to-path-for-js-nixmodules

couldn't get `bun` in there without adding pkgs-unstable to the derivation 🤷

What changed
============

added yarn and pnpm to PATH for nodejs modules

Test plan
=========

- `which yarn` in an empty repl with nodejs nixmodules installed works
- ditto with `which pnpm`

Rollout
=======

_Describe any procedures or requirements needed to roll this out safely (or check the box below)_

- [ ] This is fully backward and forward compatible

2023-10-20 23:38 UTC, ryantm commented
> couldn't get bun in there without adding pkgs-unstable to the derivation 🤷

I think you might as well add it. If it is development only, it won't affect our disk building (which already has bun) and it shouldn't bloat Deployments.

2023-10-20 23:38 UTC, ryantm requested changes

2023-10-20 23:38 UTC, ryantm commented on pkgs/modules/nodejs/default.nix
> +      nodepkgs.yarn
let's add bun too!

2023-10-20 23:40 UTC, ryantm requested changes

2023-10-20 23:40 UTC, ryantm commented on pkgs/modules/nodejs/default.nix
```suggestion
    ];
    dev.packages = [
      nodepkgs.pnpm
      nodepkgs.yarn
    ];
```

2023-10-20 23:41 UTC, ryantm commented on pkgs/modules/nodejs/default.nix
And can I think we should add bun too!

2023-10-24 17:20 UTC, ryantm reviewed
Looks good. Now we need to update the lockfile and upgrade maps!

2023-10-24 17:31 UTC, cdmistman commented
oh i forgot to push the lockfile change. no need to update upgrade maps though since the only affected modules already have linear upgrades

2023-10-24 18:59 UTC, ryantm approved these changes

2023-10-25 16:44 UTC, merged