[chore] Also upgrade python 3.8
replit/nixmodules pull request #258
Opened 2024-02-06 23:29 UTC by blast-hardcheese

Why
===

#256 had 3.8, but #257 skipped it. Tested locally, it seems to work, so upgrading that as well.

What changed
============

python 3.8 is no longer special-cased to 23_05.

Test plan
=========

Install python 3.8 module, try to import libraries that use native `.so` files

Rollout
=======

_Describe any procedures or requirements needed to roll this out safely (or check the box below)_

- [ ] This is fully backward and forward compatible

2024-02-06 23:31 UTC, ryantm requested changes

2024-02-06 23:31 UTC, ryantm commented on pkgs/modules/python/default.nix
> +  pkgs = pkgs-unstable;
If we're switching to pkgs-unstable, we can undo this change I was slightly complaining about here too and just reference pkgs directly: https://github.com/replit/nixmodules/pull/257/files#r1480135676

2024-02-07 14:33 UTC, airportyh commented
Hold this...gonna need to [revert the python upgrade until rtld loader lands](https://replit.slack.com/archives/C03KS2B221W/p1707315334964009) :(

2024-02-07 17:58 UTC, blast-hardcheese commented
👍 Going to punt on this change for now due to observations. In Slack, it's determined that we'll likely need to maintain 3.8 on 23_05 until we delete it.

2024-02-07 17:58 UTC, closed without merging